In [1]:
import nibabel as nib
import numpy as np

In [2]:
fmri = nib.load("data/CSI1_GLMbetas-TYPEA-ASSUMEHRF_ses-01.nii.gz")
print(fmri)


<class 'nibabel.nifti1.Nifti1Image'>
data shape (71, 89, 72, 370)
affine:
[[2. 0. 0. 2.]
 [0. 2. 0. 2.]
 [0. 0. 2. 2.]
 [0. 0. 0. 1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : np.bytes_(b'')
db_name         : np.bytes_(b'')
extents         : 0
session_error   : 0
regular         : np.bytes_(b'r')
dim_info        : 0
dim             : [  4  71  89  72 370   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 2. 2. 2. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 380305
glmin           : -248841
descrip         : np.bytes_(b'')
aux_file        : np.bytes_(b'none')
qform_code      : unkn